package mod.chiselsandbits.forge.data;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.ldtteam.datagenerators.IJsonSerializable;
import mod.chiselsandbits.platforms.core.util.constants.Constants;

public class DataGeneratorConstants
{

    private DataGeneratorConstants()
    {
        throw new IllegalStateException("Can not instantiate an instance of: DataGeneratorConstants. This is a utility class");
    }

    public static final Gson GSON     = new GsonBuilder().disableHtmlEscaping().create();
    public static final Gson GSONLang = new GsonBuilder().disableHtmlEscaping().setPrettyPrinting().create();

    private static final String DATAPACK_DIR = "data/" + Constants.MOD_ID + "/";
    private static final String RESOURCEPACK_DIR = "assets/" + Constants.MOD_ID + "/";

    // DataPack Directories \\

    public static final String LOOT_TABLES_DIR = DATAPACK_DIR + "loot_tables/blocks";

    public static final String TAGS_DIR = DATAPACK_DIR + "tags/";

    public static final String RECIPES_DIR = DATAPACK_DIR + "/recipes/";

    // ResourcePack Directories \\
    public static final String EN_US_LANG = RESOURCEPACK_DIR +  "/lang/en_us.json";
    public static final String ITEM_MODEL_DIR = RESOURCEPACK_DIR + "/models/item/";
    public static final String BLOCKSTATE_DIR = RESOURCEPACK_DIR + "blockstates/";

    /**
     * Utility method to add a "message" to the json objects before writing.
     *
     * @param serializable the serializable
     * @return the new jsonElement
     */
    public static JsonElement serialize(IJsonSerializable serializable)
    {
        JsonElement jsonElement = serializable.serialize();
        if (jsonElement.isJsonObject())
            jsonElement.getAsJsonObject().addProperty("READ ME!!!", "DO NOT EDIT THIS FILE. DON'T TOUCH IT, TOUCH IT AND YOU WILL REGRET IT ~~ AshersLab (Use the Data Generators!");
        return jsonElement;
    }
}
